name: selfcerts
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        APP_VER_TAG: ${APP_VER_TAG:-0.0.0-dev}
    image: ${REGISTRY:-registry.app.shenhe.org}/selfcerts:${APP_VER_TAG:-latest}
    container_name: selfcerts-dev-app
    restart: unless-stopped
    user: root
    ports:
      - "${APP_WEB_PORT:-8083}:80"
    volumes:
      - ./data/${APP_PROD_TAG:-dev}:/app/data
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/selfcerts.db
      - Logging__LogLevel__Default=${APP_LOG_LEVEL:-Information}
      - ASPNETCORE_ENVIRONMENT=Development